version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/jenkins.yaml
volumes:
  jenkins_home:
